name: Android CI

on: push

jobs:
  build-apk:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3.11.0
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Build debug APK
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: assembleDebug
          gradle-home-cache-cleanup: true

      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with:
          name: Debug APKs
          path: android/build/outputs/apk/debug/*.apk
